### ISSUE TITLE
aiohttp API change?

### ISSUE THREAD

**Issue by angramainyu74** [banteg/rarbg#1]
Setup appeared to be successful, but I get this when trying to run rarbg:

Traceback (most recent call last):
  File "/usr/local/bin/rarbg", line 11, in <module>
    load_entry_point('rarbg==0.2.dev0', 'console_scripts', 'rarbg')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/rarbg.py", line 10, in <module>
    from aiohttp import get, web
ImportError: cannot import name 'get'

**Comment by banteg** [comment]
You are right, this is a change from aiohttp 2.x release. I'll update the app in a moment. Thanks for report.
