### ISSUE TITLE
Trying to get this running under virtualenv

### ISSUE THREAD

**Issue by bittaurus** [banteg/rarbg#4]
```
(virtualenv3) bittaurus@palm ~/bin $ rarbg
Traceback (most recent call last):
  File "/home/bittaurus/virtualenv3/bin/rarbg", line 7, in <module>
    from rarbg import main
  File "/home/bittaurus/virtualenv3/lib/python3.4/site-packages/rarbg.py", line 53
    async def fetch_json(*args, **kwds):
            ^
SyntaxError: invalid syntax
(virtualenv3) bittaurus@palm ~/bin $ python -V
Python 3.4.6
```

Any ideas?  missing dependencies?

**Comment by banteg** [comment]
Your Python version is too old, try Python 3.6.
